#!/bin/bash
set -e

key=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 64)
bytes_password=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 20)
sed -i "s/BYTES_SECRET= *\$/BYTES_SECRET=${key}/" /etc/kat/bytes.conf
sed -i "s/BYTES_PASSWORD= *\$/BYTES_PASSWORD=${bytes_password}/" /etc/kat/bytes.conf

#DEBHELPER#

chown -R root:kat /etc/kat
chown kat:kat /var/log/kat-bytes
chown kat:kat /var/lib/kat-bytes
