[theme]
inherit = "alabaster"
pygments_style = { default = "default" }

stylesheets = [
  "css/manon_theme.css"
]

[options]
show_relbar_bottom = true
show_related = false
logo = "_static/img/logo.svg"
