# Generated by Django 5.1.11 on 2025-07-23 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("openkat", "0001_initial")]

    operations = [migrations.DeleteModel(name="OOIInformation")]
