# Generated by Django 5.2.6 on 2025-09-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openkat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('can_switch_organization', 'Can switch organization'), ('can_scan_organization', 'Can scan organization'), ('can_set_clearance_level', 'Can set clearance level'), ('can_access_all_organizations', 'Can access all organizations'), ('can_enable_disable_schedule', 'Can enable or disable schedules'))},
        ),
    ]
