# Generated by Django 5.2.6 on 2025-09-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("openkat", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="organizationmember", name="onboarded"),
        migrations.AddField(model_name="user", name="onboarded", field=models.BooleanField(default=False)),
    ]
