# Generated by Django 5.2.6 on 2025-09-23 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("openkat", "0002_remove_organizationmember_onboarded_user_onboarded")]

    operations = [migrations.RemoveField(model_name="organizationmember", name="status")]
