exclude: "/migrations/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
        exclude: ^boefjes/plugins/kat_cve_2023_34039/keys/
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
      - id: check-toml
