"""Make organisation code field larger

Revision ID: 197672984df0
Revises: 0003
Create Date: 2022-12-12 13:22:07.119970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "197672984df0"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organisation", "id", existing_type=sa.VARCHAR(length=4), type_=sa.String(length=32), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organisation", "id", existing_type=sa.String(length=32), type_=sa.VARCHAR(length=4), existing_nullable=False
    )
    # ### end Alembic commands ###
