"""Introduce Boefje and Normalizer models

Revision ID: 253a2e755df0
Revises: 7c88b9cd96aa
Create Date: 2024-05-28 09:48:11.107889

"""

import sqlalchemy as sa
from alembic import op

from boefjes.sql.db_models import ScanLevel

# revision identifiers, used by Alembic.
revision = "253a2e755df0"
down_revision = "7c88b9cd96aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boefje",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plugin_id", sa.String(length=64), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("scan_level", ScanLevel(), nullable=False),
        sa.Column("consumes", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("produces", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("environment_keys", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("oci_image", sa.String(length=256), nullable=True),
        sa.Column("oci_arguments", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plugin_id"),
    )
    op.create_table(
        "normalizer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plugin_id", sa.String(length=64), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("scan_level", ScanLevel(), nullable=False),
        sa.Column("consumes", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("produces", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("environment_keys", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plugin_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("normalizer")
    op.drop_table("boefje")
    # ### end Alembic commands ###
