"""Introduce schema field to Boefje model

Revision ID: 5be152459a7b
Revises: f9de6eb7824b
Create Date: 2024-08-08 14:47:12.582017

"""

import logging

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker

from boefjes.local_repository import get_local_repository
from boefjes.sql.plugin_storage import create_plugin_storage
from boefjes.storage.interfaces import PluginNotFound

# revision identifiers, used by Alembic.
revision = "5be152459a7b"
down_revision = "f9de6eb7824b"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boefje", sa.Column("schema", sa.JSON(), nullable=True))

    local_repo = get_local_repository()
    session = sessionmaker(bind=op.get_bind())()

    with create_plugin_storage(session) as storage:
        for plugin in local_repo.get_all():
            if schema := local_repo.schema(plugin.id):
                try:
                    # This way we avoid the safeguard that updating static boefjes is not allowed
                    instance = storage._db_boefje_instance_by_id(plugin.id)
                    instance.schema = schema
                    storage.session.add(instance)
                    logger.info("Updated database entry for plugin %s", plugin.id)
                except PluginNotFound:
                    logger.info("No database entry for plugin %s", plugin.id)
                    continue

    session.close()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boefje", "schema")
    # ### end Alembic commands ###
