"""Unique plugin names

Revision ID: a2c8d54b0124
Revises: 870fc302b852
Create Date: 2024-09-18 14:46:00.881022

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a2c8d54b0124"
down_revision = "870fc302b852"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_boefje_name", "boefje", ["name"])
    op.create_unique_constraint("unique_normalizer_name", "normalizer", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_normalizer_name", "normalizer", type_="unique")
    op.drop_constraint("unique_boefje_name", "boefje", type_="unique")
    # ### end Alembic commands ###
