"""Add run on field to boefje

Revision ID: fc0295b38184
Revises: 9f48560b0000
Create Date: 2025-02-04 16:43:59.171960

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc0295b38184"
down_revision = "9f48560b0000"
branch_labels = None
depends_on = None


run_on = sa.Enum("create", "update", "create_update", name="run_on")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    run_on.create(op.get_bind())
    op.add_column("boefje", sa.Column("run_on", run_on, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boefje", "run_on")
    run_on.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
