"""Add deduplication flag

Revision ID: fdeaea4481b8
Revises: fc0295b38184
Create Date: 2025-05-28 11:45:16.215166

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fdeaea4481b8"
down_revision = "fc0295b38184"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boefje", sa.Column("deduplicate", sa.Boolean(), server_default="true", nullable=False))
    op.add_column("organisation", sa.Column("deduplicate", sa.Boolean(), server_default="true", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organisation", "deduplicate")
    op.drop_column("boefje", "deduplicate")
    # ### end Alembic commands ###
