"""Update hash field constraints

Revision ID: 0005
Revises: 0004
Create Date: 2023-04-19 12:57:51.984207

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'hash',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_unique_constraint(None, 'items', ['hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='unique')
    op.alter_column('items', 'hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
