"""Update tasks

Revision ID: 0008
Revises: 0007
Create Date: 2024-01-31 16:30:14.891313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('pending', sa.Interval(), nullable=True))
    op.add_column('tasks', sa.Column('queued', sa.Interval(), nullable=True))
    op.add_column('tasks', sa.Column('dispatched', sa.Interval(), nullable=True))
    op.add_column('tasks', sa.Column('running', sa.Interval(), nullable=True))
    op.add_column('tasks', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_tasks_p_item_hash', table_name='tasks')
    op.create_index('ix_p_item_hash', 'tasks', [sa.text("(p_item->>'hash')"), sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_p_item_hash', table_name='tasks')
    op.create_index('ix_tasks_p_item_hash', 'tasks', [sa.text("(p_item ->> 'hash'::text)"), sa.text('created_at DESC')], unique=False)
    op.drop_column('tasks', 'meta')
    op.drop_column('tasks', 'running')
    op.drop_column('tasks', 'dispatched')
    op.drop_column('tasks', 'queued')
    op.drop_column('tasks', 'pending')
    # ### end Alembic commands ###
