"""Add jobs model

Revision ID: 0008
Revises: 0007
Create Date: 2024-01-16 13:09:25.846897

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import scheduler

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", scheduler.utils.datastore.GUID(), nullable=False),
        sa.Column("scheduler_id", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("p_item", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cron_expression", sa.String(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tasks", sa.Column("job_id", scheduler.utils.datastore.GUID(), nullable=True))
    op.drop_index("ix_tasks_p_item_hash", table_name="tasks")
    op.create_index("ix_p_item_hash", "tasks", [sa.text("(p_item->>'hash')"), sa.text("created_at DESC")], unique=False)
    op.create_foreign_key(None, "tasks", "jobs", ["job_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index("ix_p_item_hash", table_name="tasks")
    op.create_index(
        "ix_tasks_p_item_hash",
        "tasks",
        [sa.text("(p_item ->> 'hash'::text)"), sa.text("created_at DESC")],
        unique=False,
    )
    op.drop_column("tasks", "job_id")
    op.drop_table("jobs")
    # ### end Alembic commands ###
