"""Update task status

Revision ID: 0008
Revises: 0007
Create Date: 2024-03-04 13:22:43.852507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('pending_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('running_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_tasks_p_item_hash', table_name='tasks')
    op.create_index('ix_p_item_hash', 'tasks', [sa.text("(p_item->>'hash')"), sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_p_item_hash', table_name='tasks')
    op.create_index('ix_tasks_p_item_hash', 'tasks', [sa.text("(p_item ->> 'hash'::text)"), sa.text('created_at DESC')], unique=False)
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'running_at')
    op.drop_column('tasks', 'dispatched_at')
    op.drop_column('tasks', 'queued_at')
    op.drop_column('tasks', 'pending_at')
    op.drop_column('tasks', 'meta')
    # ### end Alembic commands ###
