"""Add DELAYED status for tasks

Revision ID: 0008
Revises: 0007_add_cancelled_status_for_tasks
Create Date: 2023-07-24 12:22:42.329666

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus ADD VALUE 'DELAYED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus DROP VALUE 'DELAYED'")
    # ### end Alembic commands ###
