"""Add tasks trigger

Revision ID: 0009_add_tasks_trigger
Revises: 0008
Create Date:

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0009_add_tasks_trigger"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """CREATE OR REPLACE FUNCTION tasks_trigger() RETURNS trigger AS $$
           BEGIN
             IF (TG_OP = 'UPDATE') THEN
               PERFORM pg_notify('update_task', json_build_object('id', NEW.id, 'status', NEW.status)::text);
             END IF;
             RETURN NEW;
           END;
           $$ LANGUAGE plpgsql;"""
    )
    op.execute("DROP TRIGGER IF EXISTS tasks_trigger ON tasks;")
    op.execute("CREATE TRIGGER tasks_trigger AFTER UPDATE ON tasks FOR EACH ROW EXECUTE PROCEDURE tasks_trigger();")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS tasks_trigger ON tasks")
    # ### end Alembic commands ###
