global:
  scrape_interval: 15s

  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 5s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "scheduler"

    scrape_interval: 1s

    static_configs:
      - targets: ["scheduler:8000"]
