# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="batch_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override the global BATCH_SIZE setting for this plugin. Set to 0 to disable batching.",
                null=True,
            ),
        )
    ]
