# Generated by Django 5.1.11 on 2025-08-22 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="oci_arguments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=256), default=list, size=None
            ),
        )
    ]
