# Generated by Django 5.2.6 on 2025-10-03 15:22
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0002_plugin_batch_size")]

    operations = [
        migrations.CreateModel(
            name="BusinessRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("finding_type_code", models.CharField(max_length=100)),
                (
                    "object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("query", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
