# Generated by Django 5.1.11 on 2025-08-29 12:17

import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0002_alter_plugin_oci_arguments")]

    operations = [
        migrations.AlterField(model_name="plugin", name="description", field=models.TextField(blank=True, null=True)),
        migrations.AlterField(
            model_name="plugin", name="recurrences", field=recurrence.fields.RecurrenceField(blank=True, null=True)
        ),
    ]
