# Generated by Django 5.2.6 on 2025-10-07 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0003_businessrule")]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="consumes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=128), blank=True, default=list, size=None
            ),
        )
    ]
