# Generated by Django 5.2.7 on 2025-10-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0004_alter_plugin_consumes")]

    operations = [
        migrations.AddField(
            model_name="businessrule",
            name="inverse_query",
            field=models.TextField(help_text="Query to remove findings that no longer apply"),
        )
    ]
