# Generated by Django 5.2.7 on 2025-10-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0005_businessrule_inverse_query")]

    operations = [
        migrations.AlterField(
            model_name="businessrule",
            name="query",
            field=models.TextField(help_text="Query to find objects that should get a finding"),
        )
    ]
