# Generated by Django 5.2.7 on 2025-10-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0006_alter_businessrule_query")]

    operations = [
        migrations.AlterField(
            model_name="businessrule",
            name="inverse_query",
            field=models.TextField(blank=True, help_text="Query to remove findings that no longer apply", null=True),
        )
    ]
