# Generated by Django 5.2.7 on 2025-10-16 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("plugins", "0007_alter_businessrule_inverse_query")]

    operations = [migrations.DeleteModel(name="EnabledPlugin")]
