# Generated by Django 5.2.7 on 2025-10-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0008_delete_enabledplugin")]

    operations = [
        migrations.AlterField(
            model_name="businessrule",
            name="finding_type_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="businessrule",
            name="query",
            field=models.TextField(blank=True, help_text="Query to find objects that should get a finding", null=True),
        ),
    ]
