# Generated by Django 5.2.7 on 2025-10-24 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0009_alter_businessrule_finding_type_code_and_more")]

    operations = [
        migrations.AddField(
            model_name="businessrule",
            name="requires",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=256), default=list, size=None
            ),
        )
    ]
