# Generated by Django 5.2.7 on 2025-10-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0010_businessrule_requires")]

    operations = [
        migrations.RemoveField(model_name="businessrule", name="requires"),
        migrations.AddField(
            model_name="businessrule",
            name="requires",
            field=models.ManyToManyField(related_name="required_by", to="plugins.plugin"),
        ),
    ]
