# Generated by Django 5.2.7 on 2025-10-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0011_remove_businessrule_requires_businessrule_requires")]

    operations = [
        migrations.AlterField(
            model_name="businessrule",
            name="requires",
            field=models.ManyToManyField(blank=True, related_name="required_by", to="plugins.plugin"),
        )
    ]
