# Generated by Django 5.2.7 on 2025-11-10 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("plugins", "0012_alter_businessrule_requires")]

    operations = [
        migrations.AlterModelOptions(
            name="businessrule", options={"permissions": [("run_businessrule", "Can run a business rule")]}
        )
    ]
