# Generated by Django 5.2.8 on 2025-11-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0013_alter_businessrule_options")]

    operations = [migrations.AddField(model_name="plugin", name="permissions", field=models.JSONField(default=dict))]
