# Generated by Django 5.1.9 on 2025-06-07 10:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("openkat", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Boefje",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plugin_id", models.CharField(max_length=64, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("static", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(null=True)),
                (
                    "scan_level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "L0"), (1, "L1"), (2, "L2"), (3, "L3"), (4, "L4")], default=4
                    ),
                ),
                (
                    "consumes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128), default=list, size=None
                    ),
                ),
                (
                    "produces",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128), default=list, size=None
                    ),
                ),
                ("schema", models.JSONField(null=True)),
                ("cron", models.CharField(max_length=128, null=True)),
                ("interval", models.IntegerField(null=True)),
                (
                    "run_on",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("create_update", "Create Update")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("oci_image", models.CharField(max_length=256, null=True)),
                (
                    "oci_arguments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128), default=list, size=None
                    ),
                ),
                ("version", models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Normalizer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plugin_id", models.CharField(max_length=64, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("static", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(null=True)),
                (
                    "consumes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128), default=list, size=None
                    ),
                ),
                (
                    "produces",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128), default=list, size=None
                    ),
                ),
                ("version", models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BoefjeConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("settings", models.CharField(db_default="{}", max_length=512)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "boefje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boefje_configs",
                        to="katalogus.boefje",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boefje_configs",
                        to="openkat.organization",
                    ),
                ),
            ],
            options={"unique_together": {("boefje", "organization")}},
        ),
        migrations.CreateModel(
            name="NormalizerConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("settings", models.CharField(db_default="{}", max_length=512)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "normalizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalizer_configs",
                        to="katalogus.normalizer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalizer_configs",
                        to="openkat.organization",
                    ),
                ),
            ],
            options={"unique_together": {("normalizer", "organization")}},
        ),
    ]
