# Generated by Django 5.1.9 on 2025-07-17 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("katalogus", "0001_initial"), ("openkat", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="boefjeconfig",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boefje_configs",
                to="openkat.organization",
            ),
        ),
        migrations.AlterField(
            model_name="normalizerconfig",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normalizer_configs",
                to="openkat.organization",
            ),
        ),
    ]
