# Generated by Django 5.1.11 on 2025-07-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("katalogus", "0001_initial"), ("openkat", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="boefjeconfig",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boefje_configs",
                to="openkat.organization",
            ),
        ),
        migrations.AddField(
            model_name="normalizerconfig",
            name="normalizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normalizer_configs",
                to="katalogus.normalizer",
            ),
        ),
        migrations.AddField(
            model_name="normalizerconfig",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normalizer_configs",
                to="openkat.organization",
            ),
        ),
        migrations.AlterUniqueTogether(name="boefjeconfig", unique_together={("boefje", "organization")}),
        migrations.AlterUniqueTogether(name="normalizerconfig", unique_together={("normalizer", "organization")}),
    ]
