# Generated by Django 3.2.14 on 2022-07-14 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("account", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="katuser", name="first_name"),
        migrations.RemoveField(model_name="katuser", name="last_name"),
    ]
