# Generated by Django 4.2.1 on 2023-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_first_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="katuser",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="full name"),
        ),
    ]
