#!/bin/bash
set -e
if [ "$1" = "remove" -o "$1" = "purge" ]; then
    if [ -d /usr/share/kat-mula ]; then
        rm -r /usr/share/kat-mula
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge
    fi

    rm /etc/kat/mula.conf || true
    rm /etc/kat/logging.mula.json || true
fi
