#!/bin/bash
set -e

if [ "$1" = "remove" -o "$1" = "purge" ]; then
    if [ -d /usr/share/kat-boefjes ]; then
        rm -r /usr/share/kat-boefjes
    fi

    if [ -f /etc/nginx/sites-enabled/kat-katalogus ]; then
        rm /etc/nginx/sites-enabled/kat-katalogus
        systemctl reload nginx
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge
    fi

    if [ -f /etc/kat/boefjes ]; then
        rm /etc/kat/boefjes.conf
    fi
fi
