#!/bin/sh -e

if [ -f /etc/nginx/sites-enabled/kat-katalogus ]; then
    rm /etc/nginx/sites-enabled/kat-katalogus
    systemctl reload nginx
fi

systemctl disable --now kat-katalogus.socket
systemctl disable --now kat-katalogus.service
systemctl disable --now kat-boefjes.service
systemctl disable --now kat-normalizers.service
