# Generated by Django 5.1.11 on 2025-07-23 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name="DashboardData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipe", models.UUIDField(null=True)),
                ("template", models.CharField(blank=True, default="findings_report/report.html", max_length=126)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=1,
                        help_text="Where on the dashboard do you want to show the data? Position 1 is the most top level and the max position is 16.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16),
                        ],
                    ),
                ),
                (
                    "display_in_crisis_room",
                    models.BooleanField(
                        default=False, help_text="Will be displayed on the general crisis room, for all organizations."
                    ),
                ),
                (
                    "display_in_dashboard",
                    models.BooleanField(
                        default=False, help_text="Will be displayed on a single organization dashboard"
                    ),
                ),
                (
                    "findings_dashboard",
                    models.BooleanField(
                        default=False, help_text="Will be displayed on the findings dashboard for all organizations"
                    ),
                ),
            ],
        ),
    ]
