# Generated by Django 5.1.11 on 2025-07-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("crisis_room", "0001_initial"), ("openkat", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="openkat.organization"),
        ),
        migrations.AddField(
            model_name="dashboarddata",
            name="dashboard",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="crisis_room.dashboard"),
        ),
        migrations.AlterUniqueTogether(name="dashboard", unique_together={("name", "organization")}),
        migrations.AlterUniqueTogether(
            name="dashboarddata", unique_together={("dashboard", "findings_dashboard"), ("dashboard", "position")}
        ),
    ]
