#!/bin/bash -e

set -e

# Set SECRET_KEY if empty
key=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 64)
sed -i "s/SECRET_KEY= *\$/SECRET_KEY=${key}/" /etc/kat/rocky.conf

# TODO: skip on upgrade
if [ ! -f /etc/kat/rocky.local.crt ]; then
    openssl req -x509 -newkey rsa:4096 \
        -keyout /etc/kat/rocky.local.key \
        -out /etc/kat/rocky.local.crt -sha256 \
        -days 365 -nodes -subj '/CN=rocky.local'
fi

#DEBHELPER#

chown -R root:kat /etc/kat
chown root:kat /etc/kat/rocky.local.key
chown root:kat /etc/kat/rocky.local.crt
chmod 640 /etc/kat/rocky.local.{key,crt}
