# Generated by Django 5.2.7 on 2025-10-21 11:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0002_initial"),
        ("openkat", "0003_remove_organizationmember_status"),
        ("tasks", "0006_schedule_report_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "finding_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), blank=True, default=list, size=None
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="report", to="files.file"
                    ),
                ),
                (
                    "object_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="tasks.objectset",
                    ),
                ),
                (
                    "organizations",
                    models.ManyToManyField(blank=True, related_name="filtered_reports", to="openkat.organization"),
                ),
            ],
        )
    ]
