version: 1
disable_existing_loggers: 0

formatters:
  default:
    format: '%(asctime)s [%(process)d] [%(levelname)s] [%(module)s] %(message)s'
    datefmt: '[%Y-%m-%d %H:%M:%S %z]'

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
    stream: ext://sys.stdout
  syslog:
    class: logging.handlers.SysLogHandler
    formatter: default
    address: /dev/log
    facility: local0

root:
    level: INFO
    handlers: [console, syslog]

loggers:
  uvicorn:
    level: INFO
    propagate: 0
    handlers: [console, syslog]
  pika:
    level: WARN
    handlers: [console, syslog]
    propagate: 0
  api:
    LEVEL: INFO
    handlers: [console, syslog]
    propagate: 0
