"""Update tasks

Revision ID: 0002
Revises: 0001
Create Date: 2022-11-02 10:33:34.403970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", scheduler.utils.datastore.GUID(), nullable=False),
        sa.Column("scheduler_id", sa.String(), nullable=True),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tasks", sa.Column("p_item", sa.JSON(), nullable=False))
    op.drop_column("tasks", "task")
    op.drop_column("tasks", "hash")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("hash", sa.VARCHAR(), nullable=True))
    op.add_column("tasks", sa.Column("task", sqlite.JSON(), nullable=False))
    op.drop_column("tasks", "p_item")
    op.drop_table("items")
    # ### end Alembic commands ###
