# Generated by Django 5.1.11 on 2025-07-25 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tasks", "0001_initial")]

    operations = [migrations.RemoveField(model_name="task", name="priority")]
