# Generated by Django 5.1.9 on 2025-07-17 06:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tasks", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="rawfile",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=128), default=list, size=None
            ),
        )
    ]
