# Generated by Django 5.2.6 on 2025-09-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contenttypes", "0002_remove_content_type_name"), ("tasks", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="objectset",
            name="object_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
            preserve_default=False,
        )
    ]
