# Generated by Django 5.1.9 on 2025-07-17 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tasks", "0002_rawfile_tags"), ("openkat", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="openkat.organization"
            ),
        )
    ]
