# Generated by Django 5.1.11 on 2025-08-26 18:09

import django.db.models.deletion
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("openkat", "0001_initial"), ("tasks", "0002_remove_task_priority")]

    operations = [
        migrations.AddField(model_name="task", name="ended_at", field=models.DateTimeField(null=True)),
        migrations.CreateModel(
            name="NewSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=True)),
                ("recurrences", recurrence.fields.RecurrenceField(null=True)),
                ("plugins", models.TextField()),
                ("input", models.TextField()),
                ("run_on", models.CharField(max_length=64, null=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")],
                        default="create",
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_schedules",
                        to="openkat.organization",
                    ),
                ),
            ],
        ),
    ]
