# Generated by Django 5.2.6 on 2025-09-23 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tasks", "0002_objectset_object_type")]

    operations = [
        migrations.AlterField(
            model_name="objectset",
            name="all_objects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=128), blank=True, default=list, size=None
            ),
        )
    ]
