# Generated by Django 5.2.6 on 2025-09-30 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tasks", "0003_alter_objectset_all_objects")]

    operations = [
        migrations.AlterField(
            model_name="objectset",
            name="all_objects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(), blank=True, default=list, size=None
            ),
        )
    ]
