# Generated by Django 5.2.6 on 2025-10-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tasks", "0004_alter_objectset_all_objects")]

    operations = [
        migrations.AlterField(
            model_name="objectset",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        )
    ]
