# Generated by Django 5.2.7 on 2025-10-20 09:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugins", "0008_delete_enabledplugin"), ("tasks", "0005_alter_objectset_name")]

    operations = [
        migrations.AddField(model_name="schedule", name="report_description", field=models.TextField(blank=True)),
        migrations.AddField(
            model_name="schedule",
            name="report_finding_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="schedule", name="report_name", field=models.CharField(blank=True, max_length=255, null=True)
        ),
        migrations.AddField(
            model_name="schedule", name="task_type", field=models.CharField(default="plugin", max_length=32)
        ),
        migrations.AlterField(
            model_name="schedule",
            name="plugin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="plugins.plugin",
            ),
        ),
    ]
