# Generated by Django 5.1.11 on 2025-08-29 12:17

import django.db.models.deletion
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("openkat", "0001_initial"), ("tasks", "0006_task_new_schedule_alter_newschedule_input_and_more")]

    operations = [
        migrations.AlterField(
            model_name="newschedule",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_schedules",
                to="openkat.organization",
            ),
        ),
        migrations.AlterField(
            model_name="newschedule", name="recurrences", field=recurrence.fields.RecurrenceField(blank=True, null=True)
        ),
    ]
