# Generated by Django 5.2.7 on 2025-10-24 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tasks", "0006_schedule_report_description_and_more")]

    operations = [migrations.RemoveField(model_name="objectset", name="dynamic")]
