# Generated by Django 5.2.7 on 2025-11-03 09:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tasks", "0007_remove_objectset_dynamic")]

    operations = [
        migrations.AlterField(
            model_name="objectset",
            name="all_objects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        )
    ]
