# Generated by Django 5.1.11 on 2025-09-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('tasks', '0007_alter_newschedule_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschedule',
            name='object_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='objects.objectset'),
        ),
    ]
