# Generated by Django 5.2.7 on 2025-11-07 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tasks", "0008_alter_objectset_all_objects")]

    operations = [migrations.RemoveField(model_name="objectset", name="subsets")]
