# Generated by Django 5.1.11 on 2025-09-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_newschedule_object_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newschedule',
            name='input',
        ),
    ]
