# Generated by Django 5.1.11 on 2025-09-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_newschedule_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='new_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.newschedule'),
        ),
    ]
