# Generated by Django 5.1.11 on 2025-09-12 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_object_type'),
        ('openkat', '0003_alter_organization_options'),
        ('tasks', '0010_alter_task_new_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschedule',
            name='object_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='objects.objectset'),
        ),
        migrations.AlterField(
            model_name='task',
            name='new_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.newschedule'),
        ),
        migrations.AlterField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='openkat.organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.schedule'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(default='plugin', max_length=32),
        ),
    ]
