# Generated by Django 5.1.11 on 2025-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('dynamic', models.BooleanField(default=False)),
                ('object_query', models.TextField(blank=True, null=True)),
                ('all_objects', models.ManyToManyField(blank=True, related_name='object_sets', to='objects.object')),
                ('subsets', models.ManyToManyField(blank=True, related_name='supersets', to='objects.objectset')),
            ],
        ),
    ]
