# Generated by Django 5.1.11 on 2025-09-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
