# Generated by Django 5.2.6 on 2025-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("files", "0001_initial"), ("openkat", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="file", name="organizations", field=models.ManyToManyField(blank=True, to="openkat.organization")
        )
    ]
