# Generated by Django 3.2.5 on 2021-10-20 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0004_ooiinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=256)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "L0"), (1, "L1"), (2, "L2"), (3, "L3"), (4, "L4")],
                        default=0,
                    ),
                ),
                ("new", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tools.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("reference", "organization")},
            },
        ),
    ]
