# Generated by Django 3.2.5 on 2021-11-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0006_alter_organization_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="tool_module",
            new_name="module",
        ),
    ]
