# Generated by Django 3.2.4 on 2021-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0007_update_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
