# Generated by Django 3.2.10 on 2022-01-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0011_job_input_ooi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="module",
            new_name="boefje_name",
        ),
    ]
