# Generated by Django 3.2.11 on 2022-01-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0012_rename_module_job_boefje_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoefjeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boefje", models.CharField(max_length=128)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tools.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("boefje", "organization")},
            },
        ),
    ]
