# Generated by Django 3.2.11 on 2022-01-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0013_boefjeconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="dispatches",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="boefje_name",
            new_name="boefje_id",
        ),
    ]
