# Generated by Django 3.2.11 on 2022-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0014_drop_dispatches_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="input_ooi",
            field=models.TextField(null=True),
        ),
    ]
