# Generated by Django 3.2.4 on 2021-09-08 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0015_alter_job_input_ooi"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="signal_group_id",
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="signal_username",
            field=models.CharField(
                blank=True,
                max_length=126,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+99999999999'. 11 digits allowed.",
                        regex="^\\+?1?\\d{11,11}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="signal_username",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=126,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+99999999999'. 11 digits allowed.",
                        regex="^\\+?1?\\d{11,11}$",
                    )
                ],
            ),
        ),
    ]
