# Generated by Django 3.2.12 on 2022-03-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0016_organization_signal_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="tools.organization",
            ),
        ),
    ]
