# Generated by Django 3.2.12 on 2022-04-28 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0018_alter_boefjeconfig_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="user",
        ),
        migrations.RemoveField(
            model_name="scanprofile",
            name="level",
        ),
        migrations.RemoveField(
            model_name="scanprofile",
            name="user",
        ),
    ]
