# Generated by Django 3.2.13 on 2022-05-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0020_auto_20220524_1324"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoefjeConfig",
        ),
    ]
