# Generated by Django 3.2.13 on 2022-06-22 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0021_delete_boefjeconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("can_switch_organization", "Can switch organization"),
                    ("can_scan_organization", "Can scan organization"),
                    ("can_enable_disable_boefje", "Can enable or disable boefje"),
                )
            },
        ),
    ]
