# Generated by Django 3.2.13 on 2022-06-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0022_alter_organization_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScanProfile",
        ),
    ]
