# Generated by Django 3.2.15 on 2022-10-05 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0023_delete_scanprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="acknowledged_clearance_level",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="trusted_clearance_level",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
    ]
