# Generated by Django 3.2.18 on 2023-02-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0028_auto_20230117_1242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationtag",
            name="color",
            field=models.CharField(
                choices=[
                    ("color-1-light", "Blue light"),
                    ("color-1-medium", "Blue medium"),
                    ("color-1-dark", "Blue dark"),
                    ("color-2-light", "Green light"),
                    ("color-2-medium", "Green medium"),
                    ("color-2-dark", "Green dark"),
                    ("color-3-light", "Yellow light"),
                    ("color-3-medium", "Yellow medium"),
                    ("color-3-dark", "Yellow dark"),
                    ("color-4-light", "Orange light"),
                    ("color-4-medium", "Orange medium"),
                    ("color-4-dark", "Orange dark"),
                    ("color-5-light", "Red light"),
                    ("color-5-medium", "Red medium"),
                    ("color-5-dark", "Red dark"),
                    ("color-6-light", "Violet light"),
                    ("color-6-medium", "Violet medium"),
                    ("color-6-dark", "Violet dark"),
                ],
                default="color-1-light",
                max_length=20,
            ),
        ),
    ]
