# Generated by Django 3.2.18 on 2023-03-01 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0029_alter_organizationtag_color"),
        ("tools", "0030_auto_20230227_1458"),
    ]

    operations: list = []
