# Generated by Django 3.2.18 on 2023-04-07 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from tools.models import OrganizationMember


def migrate_organizationmember_status_blocked_to_blocked_attribute(apps, schema_editor):
    members = OrganizationMember.objects.all()
    for member in members:
        if member.status == OrganizationMember.STATUSES.BLOCKED:
            member.status = OrganizationMember.STATUSES.ACTIVE
            member.blocked = True


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0031_merge_20230301_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_organizationmember_status_blocked_to_blocked_attribute),
        migrations.AlterField(
            model_name="organizationmember",
            name="status",
            field=models.CharField(choices=[("active", "active"), ("new", "new")], default="new", max_length=64),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
