# Generated by Django 3.2.18 on 2023-03-29 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0031_merge_20230301_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="groups",
            field=models.ManyToManyField(related_name="members", to="auth.Group"),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
