# Generated by Django 3.2.18 on 2023-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tools", "0032_alter_organizationmember_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("can_switch_organization", "Can switch organization"),
                    ("can_scan_organization", "Can scan organization"),
                    ("can_enable_disable_boefje", "Can enable or disable boefje"),
                    ("can_set_clearance_level", "Can set clearance level"),
                    ("can_view_admin_onboarding", "Can view admin onboarding"),
                    ("can_view_redteam_onboarding", "Can view redteam onboarding"),
                )
            },
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="members", to="auth.Group"),
        ),
    ]
