# Generated by Django 3.2.18 on 2023-03-29 13:40

from django.db import migrations
from django.contrib.auth import get_user_model
from tools.models import OrganizationMember

User = get_user_model()


def migrate_user_groups_to_organizationmember(apps, schema_editor):
    members = OrganizationMember.objects.all()
    for member in members:
        user_groups = member.user.groups.all()
        for group in user_groups:
            member.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0032_auto_20230329_1337"),
    ]

    operations = [
        migrations.RunPython(migrate_user_groups_to_organizationmember),
    ]
