# Generated by Django 3.2.18 on 2023-04-24 14:27

from django.db import migrations
import tools.fields
import tools.models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0032_alter_organizationmember_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="code",
            field=tools.fields.LowerCaseSlugField(
                allow_unicode=True,
                help_text="A slug containing only lower-case unicode letters, numbers, hyphens or underscores that will be used in URLs and paths",
                max_length=32,
                unique=True,
                validators=[tools.models.organization_code_validator],
            ),
        ),
    ]
