# Generated by Django 3.2.18 on 2023-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tools", "0032_alter_organizationmember_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="members", to="auth.Group"),
        ),
    ]
