# Generated by Django 3.2.18 on 2023-04-12 14:45

from django.contrib.auth import get_user_model
from django.db import migrations
from tools.models import OrganizationMember

User = get_user_model()


def migrate_user_groups_to_organizationmember(apps, schema_editor):
    members = OrganizationMember.objects.all()
    for member in members:
        user_groups = member.user.groups.all()
        for group in user_groups:
            member.groups.add(group)


def clear_group_from_users(apps, schema_editor):
    users = User.objects.all()
    for user in users:
        user.groups.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0033_organizationmember_groups"),
    ]

    operations = [
        migrations.RunPython(migrate_user_groups_to_organizationmember),
        migrations.RunPython(clear_group_from_users),
    ]
