# Generated by Django 3.2.18 on 2023-04-21 14:44

from django.db import migrations


def add_group_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    can_delete_oois = Permission.objects.get(codename="can_delete_oois")
    try:
        redteam = Group.objects.get(name="redteam")
        admin = Group.objects.get(name="admin")
        redteam.permissions.add(can_delete_oois)
        admin.permissions.add(can_delete_oois)
    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0034_alter_organization_options"),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
