# Generated by Django 3.2.18 on 2023-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0034_copy_user_groups_to_organizationmember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("can_switch_organization", "Can switch organization"),
                    ("can_scan_organization", "Can scan organization"),
                    ("can_enable_disable_boefje", "Can enable or disable boefje"),
                    ("can_set_clearance_level", "Can set clearance level"),
                    ("can_view_admin_onboarding", "Can view admin onboarding"),
                    ("can_view_redteam_onboarding", "Can view redteam onboarding"),
                )
            },
        ),
    ]
