# Generated by Django 3.2.18 on 2023-05-04 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0035_update_ooi_delete_perm"),
        ("tools", "0035_update_perms_move_and_clear_groups"),
    ]

    operations = []
