# Generated by Django 3.2.18 on 2023-05-09 11:34

from django.db import migrations


def add_group_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    try:
        admin = Group.objects.get(name="clients")
        admin.permissions.add(Permission.objects.get(codename="can_scan_organization"))
    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0036_merge_20230504_1629"),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
