# Generated by Django 3.2.19 on 2023-05-17 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0037_alter_organization_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
