# Generated by Django 3.2.19 on 2023-05-10 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0033_alter_organization_options"),
        ("tools", "0037_alter_organization_options"),
    ]

    operations = []
