# Generated by Django 3.2.18 on 2023-05-11 15:11

from django.db import migrations


def add_group_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    try:
        clients = Group.objects.get(name="clients")
        clients.permissions.add(Permission.objects.get(codename="can_scan_organization"))
    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0037_alter_organization_options"),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
