# Generated by Django 3.2.19 on 2023-05-22 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0038_alter_organization_options"),
        ("tools", "0038_delete_job"),
    ]

    operations: list = []
