# Generated by Django 4.2.3 on 2023-07-31 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0040_admin_inherits_red_teamer_permissions"),
        ("tools", "0040_update_admin_permission"),
    ]

    operations = []
