# Generated by Django 5.1.9 on 2025-05-20 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tools", "0045_update_permissions")]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("can_switch_organization", "Can switch organization"),
                    ("can_scan_organization", "Can scan organization"),
                    ("can_enable_disable_boefje", "Can enable or disable boefje"),
                    ("can_add_boefje", "Can add new or duplicate boefjes"),
                    ("can_set_clearance_level", "Can set clearance level"),
                    ("can_delete_oois", "Can delete oois"),
                    ("can_mute_findings", "Can mute findings"),
                    ("can_view_katalogus_settings", "Can view KAT-alogus settings"),
                    ("can_set_katalogus_settings", "Can set KAT-alogus settings"),
                    ("can_recalculate_bits", "Can recalculate bits"),
                    ("can_access_all_organizations", "Can access all organizations"),
                    ("can_enable_disable_schedule", "Can enable or disable schedules"),
                ),
            },
        )
    ]
