"""Add CANCELLED status for tasks

Revision ID: 0007
Revises: 0006_add_jsonb_fields
Create Date: 2023-05-30 12:22:42.329666

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0007"
down_revision = "0006_add_jsonb_fields"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus ADD VALUE 'CANCELLED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus DROP VALUE 'CANCELLED'")
    # ### end Alembic commands ###
