"""add_organisation

Revision ID: 0009
Revises: 0008
Create Date: 2024-12-10 15:21:27.445743

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedules", sa.Column("organisation", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("organisation", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "organisation")
    op.drop_column("schedules", "organisation")
    # ### end Alembic commands ###
