"""Add organisation column to schedules and tasks

Revision ID: 0009
Revises: 0008
Create Date: 2024-12-10 15:21:27.445743

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedules", sa.Column("organisation", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("organisation", sa.String(), nullable=True))

    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
UPDATE schedules SET organisation = data->>'organization' WHERE data->>'organization' IS NOT NULL;
UPDATE schedules SET organisation = data->'raw_data'->'boefje_meta'->>'organization' WHERE data->'raw_data'->'boefje_meta'->>'organization' IS NOT NULL;
UPDATE schedules SET organisation = data->>'organisation_id' WHERE data->>'organisation_id' IS NOT NULL;

UPDATE tasks SET organisation = data->>'organization' WHERE type = 'boefje';
UPDATE tasks SET organisation = data->'raw_data'->'boefje_meta'->>'organization' WHERE type = 'normalizer';
UPDATE tasks SET organisation = data->>'organisation_id' WHERE type = 'report';
"""  # noqa: E501
        )
    )

    op.alter_column("schedules", "organisation", nullable=False)
    op.alter_column("tasks", "organisation", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "organisation")
    op.drop_column("schedules", "organisation")
    # ### end Alembic commands ###
