"""add_schedulers

Revision ID: 0009
Revises: 0008
Create Date: 2024-11-07 11:21:16.528354

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedulers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("maxsize", sa.Integer(), nullable=False),
        sa.Column("organisation", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("BOEFJE", "NORMALIZER", "REPORT", name="schedulertype"), nullable=False),
        sa.Column("allow_replace", sa.Boolean(), nullable=True),
        sa.Column("allow_updates", sa.Boolean(), nullable=True),
        sa.Column("allow_priority_updates", sa.Boolean(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedulers")
    # ### end Alembic commands ###
