"""Add indices

Revision ID: 0010
Revises: 0009
Create Date: 2025-03-13 12:12:30.794149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_scheduler_id'), 'tasks', ['scheduler_id'], unique=False)
    op.create_index('ix_tasks_status_queued', 'tasks', ['status'], unique=False, postgresql_where=sa.text("status = 'QUEUED'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status_queued', table_name='tasks', postgresql_where=sa.text("status = 'QUEUED'"))
    op.drop_index(op.f('ix_tasks_scheduler_id'), table_name='tasks')
    # ### end Alembic commands ###
