"""Add indices

Revision ID: 0010
Revises: 0009
Create Date: 2025-03-13 14:55:52.559484

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tasks_status_queued",
        "tasks",
        ["scheduler_id", "status"],
        unique=False,
        postgresql_where=sa.text("status = 'QUEUED'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_status_queued", table_name="tasks", postgresql_where=sa.text("status = 'QUEUED'"))
    # ### end Alembic commands ###
