"""Add DELAYED status for tasks
Revision ID: 0010
Revises: 0009
Create Date: 2023-07-24 12:22:42.329666
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus ADD VALUE 'DELAYED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus DROP VALUE 'DELAYED'")
    # ### end Alembic commands ###
