import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    with conn.begin():
        conn.execute(
            sa.text(
                """
UPDATE schedules set organisation = data->>'organization';
UPDATE tasks set organisation = data->>'organization';
ALTER TABLE schedules ALTER COLUMN organisation SET NOT NULL;
ALTER TABLE tasks ALTER COLUMN organisation SET NOT NULL;
"""
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
