"""Add more indexes

Revision ID: 0011
Revises: 0010
Create Date: 2026-02-17 09:21:58.416181

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_schedules_enabled", "schedules", ["enabled"], unique=False)
    op.create_index("ix_schedules_hash", "schedules", ["hash"], unique=False)
    op.create_index("ix_schedules_organisation", "schedules", ["organisation"], unique=False)
    op.create_index("ix_schedules_scheduler_id", "schedules", ["scheduler_id"], unique=False)
    op.execute(
        """
        WITH duplicate_active_tasks AS (
            SELECT id
            FROM (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY schedule_id
                        ORDER BY created_at DESC, id DESC
                    ) AS row_number
                FROM tasks
                WHERE status IN ('PENDING', 'QUEUED', 'DISPATCHED', 'RUNNING')
                  AND schedule_id IS NOT NULL
            ) ranked
            WHERE row_number > 1
        )
        UPDATE tasks
        SET status = 'FAILED'
        WHERE id IN (
            SELECT id
            FROM duplicate_active_tasks
        )
        """
    )
    op.create_index(
        "ix_tasks_active_per_schedule",
        "tasks",
        ["schedule_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'QUEUED', 'DISPATCHED', 'RUNNING')"),
    )
    op.create_index("ix_tasks_organisation", "tasks", ["organisation"], unique=False)
    op.create_index("ix_tasks_scheduler_id", "tasks", ["scheduler_id"], unique=False)
    op.create_index("ix_tasks_status", "tasks", ["status"], unique=False)
    op.create_index("ix_tasks_type", "tasks", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_type", table_name="tasks")
    op.drop_index("ix_tasks_status", table_name="tasks")
    op.drop_index("ix_tasks_scheduler_id", table_name="tasks")
    op.drop_index("ix_tasks_organisation", table_name="tasks")
    op.drop_index(
        "ix_tasks_active_per_schedule",
        table_name="tasks",
        postgresql_where=sa.text("status IN ('PENDING', 'QUEUED', 'DISPATCHED', 'RUNNING')"),
    )
    op.drop_index("ix_schedules_scheduler_id", table_name="schedules")
    op.drop_index("ix_schedules_organisation", table_name="schedules")
    op.drop_index("ix_schedules_hash", table_name="schedules")
    op.drop_index("ix_schedules_enabled", table_name="schedules")
    # ### end Alembic commands ###
