"""Missing

Revision ID: 0014
Revises: 0013
Create Date: 2026-08-13 18:07:41.443105

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tasks_scheduler_created_status",
        "tasks",
        ["scheduler_id", sa.literal_column("created_at DESC"), "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_scheduler_created_status", table_name="tasks")
    # ### end Alembic commands ###
