FROM fedora:latest

RUN dnf install -y python3.11
RUN dnf install -y python3-pip
RUN pip3.11 install mitmproxy

RUN dnf install -y fedora-workstation-repositories
RUN dnf install -y dnf-plugin-config-manager
RUN dnf config-manager --set-enabled google-chrome
RUN dnf install -y google-chrome-stable