# Generated by Django 4.2.11 on 2024-05-09 14:19

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("fmea", "0001_initial"),
        ("fmea", "0002_auto_20220120_0839"),
        ("fmea", "0003_auto_20220203_1534"),
        ("fmea", "0004_remove_failuremode_effect_and_more"),
    ]

    initial = True

    dependencies: list = []

    operations: list = []
