# Generated by Django 3.2.11 on 2022-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmea", "0002_auto_20220120_0839"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureModeEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effect", models.TextField(max_length=256, unique=True)),
                (
                    "severity_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            ("", "--- Select an option ----"),
                            (1, "Level 1: Not Severe"),
                            (2, "Level 2: Harmful"),
                            (3, "Level 3: Severe"),
                            (4, "Level 4: Very Harmful"),
                            (5, "Level 5: Catastrophic"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="failuremode",
            name="severity_level",
        ),
        migrations.AddField(
            model_name="failuremode",
            name="critical_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="failuremode",
            name="risk_priority_number",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="failuremode",
            name="effect",
        ),
        migrations.AddField(
            model_name="failuremode",
            name="effect",
            field=models.ManyToManyField(to="fmea.FailureModeEffect"),
        ),
    ]
