# Generated by Django 5.0.9 on 2024-12-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("tools", "0044_alter_organization_options")]

    operations = [
        migrations.CreateModel(
            name="DashboardData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recipe",
                    models.CharField(
                        blank=True,
                        help_text="The recipe will be automatically created once you create a dashboard for an organization. This is the recipe id.",
                        max_length=126,
                        unique=True,
                    ),
                ),
                ("chapter", models.CharField(blank=True, max_length=126)),
                ("sort", models.CharField(blank=True, max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=126, unique=True)),
                (
                    "organization",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="tools.organization"),
                ),
                (
                    "data",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="crisis_room.dashboarddata"
                    ),
                ),
            ],
        ),
    ]
