# Generated by Django 5.0.9 on 2024-12-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("tools", "0044_alter_organization_options")]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipe", models.CharField(help_text="Recipe ID", max_length=126, unique=True)),
                (
                    "organization",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="tools.organization"),
                ),
            ],
        )
    ]
