# Generated by Django 5.0.13 on 2025-04-07 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0001_initial")]

    operations: list = []
