# Generated by Django 5.0.9 on 2024-12-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0001_initial")]

    operations = [
        migrations.AddField(model_name="dashboarddata", name="crisis_room", field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name="dashboarddata",
            name="template",
            field=models.CharField(blank=True, default="findings_report/report.html", max_length=126),
        ),
    ]
