# Generated by Django 5.0.13 on 2025-04-22 12:19

import django.core.validators
from django.db import migrations, models

import crisis_room.models


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0002_create_findings_dashboards")]

    operations = [
        migrations.AlterUniqueTogether(name="dashboarddata", unique_together={("dashboard", "position")}),
        migrations.AddField(
            model_name="dashboarddata", name="name", field=models.CharField(blank=True, max_length=126, null=True)
        ),
        migrations.AddField(model_name="dashboarddata", name="query", field=models.CharField(blank=True, null=True)),
        migrations.AddField(
            model_name="dashboarddata", name="query_from", field=models.CharField(blank=True, max_length=32, null=True)
        ),
        migrations.AddField(
            model_name="dashboarddata",
            name="settings",
            field=models.JSONField(
                blank=True, default=crisis_room.models.get_default_dashboard_data_settings, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dashboarddata",
            name="position",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Where on the dashboard do you want to show the data? Position 1 is the most top level and the max position is 16.",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)],
            ),
        ),
        migrations.AlterField(model_name="dashboarddata", name="recipe", field=models.UUIDField(blank=True, null=True)),
        migrations.AlterUniqueTogether(
            name="dashboarddata", unique_together={("dashboard", "name"), ("dashboard", "position")}
        ),
    ]
