# Generated by Django 5.0.14 on 2025-05-07 10:34

import django.core.validators
import django.db.models.constraints
import django.utils.timezone
from django.db import migrations, models

import crisis_room.models


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0002_create_findings_dashboards")]

    operations = [
        migrations.AlterUniqueTogether(name="dashboarddata", unique_together=set()),
        migrations.AddField(
            model_name="dashboard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(model_name="dashboard", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AddField(
            model_name="dashboarddata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dashboarddata", name="name", field=models.CharField(blank=True, max_length=126)
        ),
        migrations.AddField(model_name="dashboarddata", name="query", field=models.CharField(blank=True)),
        migrations.AddField(
            model_name="dashboarddata", name="query_from", field=models.CharField(blank=True, max_length=32)
        ),
        migrations.AddField(
            model_name="dashboarddata",
            name="settings",
            field=models.JSONField(
                blank=True, default=crisis_room.models.get_default_dashboard_item_settings, null=True
            ),
        ),
        migrations.AddField(model_name="dashboarddata", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name="dashboarddata",
            name="position",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Where on the dashboard do you want to show the data? Position 1 is the most top level and the max position is 16.",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)],
            ),
        ),
        migrations.AlterField(model_name="dashboarddata", name="recipe", field=models.UUIDField(blank=True, null=True)),
        migrations.AddConstraint(
            model_name="dashboarddata",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("dashboard", "position"),
                name="unique dashboard position",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboarddata",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("dashboard", "name"),
                name="unique dashboard name",
            ),
        ),
        migrations.AlterModelOptions(
            name="dashboarddata",
            options={
                "permissions": [
                    ("change_dashboarddata_position", "Can change position up or down of a dashboard item.")
                ]
            },
        ),
    ]
