# Generated by Django 5.0.9 on 2024-12-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0002_dashboarddata_crisis_room_and_more")]

    operations = [
        migrations.RenameField(model_name="dashboarddata", old_name="crisis_room", new_name="display_in_crisis_room"),
        migrations.AddField(
            model_name="dashboarddata", name="display_in_dashboard", field=models.BooleanField(default=False)
        ),
    ]
