# Generated by Django 5.0.14 on 2025-05-07 10:35

from django.db import migrations

from crisis_room.models import FINDINGS_DASHBOARD_NAME, Dashboard


def change_name_findings_dashboard(_apps, _schema_editor):
    dashboards = Dashboard.objects.filter(name="Crisis Room Findings Dashboard")
    for dashboard in dashboards:
        dashboard.name = FINDINGS_DASHBOARD_NAME
        dashboard.save()


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0003_alter_dashboarddata_unique_together_and_more")]

    operations = [migrations.RunPython(change_name_findings_dashboard)]
