# Generated by Django 5.0.9 on 2024-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0003_rename_crisis_room_dashboarddata_display_in_crisis_room_and_more")]

    operations = [
        migrations.AddField(
            model_name="dashboarddata",
            name="findings_dashboard",
            field=models.BooleanField(
                default=False, help_text="Will be displayed on the findings dashboard for all organizations"
            ),
        ),
        migrations.AlterField(
            model_name="dashboarddata",
            name="display_in_crisis_room",
            field=models.BooleanField(
                default=False, help_text="Will be displayed on the general crisis room, for all organizations."
            ),
        ),
        migrations.AlterField(
            model_name="dashboarddata",
            name="display_in_dashboard",
            field=models.BooleanField(default=False, help_text="Will be displayed on a single organization dashboard"),
        ),
    ]
