# Generated by Django 5.0.14 on 2025-05-07 10:36

import structlog
from django.contrib.auth.management import create_permissions
from django.db import migrations

logger = structlog.get_logger(__name__)


# https://stackoverflow.com/a/40092780/1336275
def migrate_permissions(apps, _schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def get_permissions(apps, codenames) -> list[str]:
    Permission = apps.get_model("auth", "Permission")
    permission_ids = []
    if codenames:
        for codename in codenames:
            try:
                permission = Permission.objects.get(codename=codename)
                permission_ids.append(permission)
            except Permission.DoesNotExist:
                logger.error("Permission code '%s' not found.", codename)
                continue

    return permission_ids


def add_dashboard_permissions_to_groups(apps, _):
    dashboard_permissions = [
        "add_dashboard",
        "change_dashboard",
        "delete_dashboard",
        "view_dashboard",
        "add_dashboarddata",
        "change_dashboarddata",
        "delete_dashboarddata",
        "view_dashboarddata",
        "change_dashboarddata_position",
    ]

    dashboard_permissions = get_permissions(apps, dashboard_permissions)
    for dashboard_permission in dashboard_permissions:
        try:
            Group = apps.get_model("auth", "Group")
            admin_group = Group.objects.get(name="admin")
            redteam_group = Group.objects.get(name="redteam")

            admin_group.permissions.add(dashboard_permission)
            redteam_group.permissions.add(dashboard_permission)
        except Group.DoesNotExist:
            continue


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0004_change_name_findings_dashboard")]

    operations = [migrations.RunPython(migrate_permissions), migrations.RunPython(add_dashboard_permissions_to_groups)]
