# Generated by Django 5.1.9 on 2025-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0005_add_dashboard_permissions_to_groups")]

    operations = [
        migrations.AddConstraint(
            model_name="dashboarddata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("findings_dashboard", True)),
                fields=("findings_dashboard",),
                name="findings_dashboard",
            ),
        )
    ]
