# Generated by Django 5.1.9 on 2025-06-10 08:01
import json
from datetime import datetime, timezone

from django.db import migrations

from crisis_room.models import DashboardItem


def change_query_params(_apps, _schema_editor):
    dashboard_items = DashboardItem.objects.all()
    new_query = {}
    for dashboard_item in dashboard_items:
        if dashboard_item.query:
            query = json.loads(dashboard_item.query)
            new_query["observed_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            new_query["ooi_type"] = query.get("ooi_types", [])
            new_query["clearance_level"] = query.get("scan_level", [])
            new_query["clearance_type"] = query.get("scan_profile_type", [])
            new_query["search"] = query.get("search_string", "")
            new_query["order_by"] = query.get("order_by", "object_type")
            new_query["sorting_order"] = query.get("asc_desc", "asc")
            new_query["limit"] = query.get("limit", 20)

            dashboard_item.query = json.dumps(new_query)
            dashboard_item.save()


class Migration(migrations.Migration):
    dependencies = [("crisis_room", "0006_rename_dashboarddata_dashboarditem")]

    operations = [
        migrations.RenameField(model_name="dashboarditem", old_name="query_from", new_name="source"),
        migrations.RunPython(change_query_params),
    ]
