"""Rename Module to Normalizer/Boefje

Revision ID: 0003
Revises: 5363940815bb
Create Date: 2021-12-20 13:25:08.395995

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "5363940815bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("boefje_meta", "module_path", new_column_name="boefje_name")
    op.alter_column("boefje_meta", "module_version", new_column_name="boefje_version")

    op.alter_column("normalizer_meta", "module_path", new_column_name="normalizer_name")
    op.alter_column("normalizer_meta", "module_version", new_column_name="normalizer_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("boefje_meta", "boefje_name", new_column_name="module_path")
    op.alter_column("boefje_meta", "boefje_version", new_column_name="module_version")

    op.alter_column("normalizer_meta", "normalizer_name", new_column_name="module_path")
    op.alter_column("normalizer_meta", "normalizer_version", new_column_name="module_version")
    # ### end Alembic commands ###
