"""Rename boefje_name to boefje_id

Revision ID: 0004
Revises: 0003
Create Date: 2022-01-24 15:53:16.867896

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("boefje_meta", "boefje_name", new_column_name="boefje_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("boefje_meta", "boefje_id", new_column_name="boefje_name")
    # ### end Alembic commands ###
