"""Max length on varchar's

Revision ID: 0010
Revises: 0009
Create Date: 2022-06-17 07:44:33.849746

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_file",
        "hash_retrieval_link",
        existing_type=sa.String(length=128),
        type_=sa.String(length=2048),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_file",
        "hash_retrieval_link",
        existing_type=sa.String(length=2048),
        type_=sa.String(length=128),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
