"""Rename normalizer_name to normalizer_id

Revision ID: 0011
Revises: 0010
Create Date: 2022-10-25 09:13:21.807003

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0011_2"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("normalizer_meta", "normalizer_name", new_column_name="normalizer_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("normalizer_meta", "normalizer_id", new_column_name="normalizer_name")
    # ### end Alembic commands ###
