"""Add signing provider to RawFile field

Revision ID: 3abbe27db591
Revises: ec68d3eb14b1
Create Date: 2023-05-16 13:17:28.002568

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3abbe27db591"
down_revision = "ec68d3eb14b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raw_file", sa.Column("signing_provider", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_file", "signing_provider")
    # ### end Alembic commands ###
