"""Increase organization and input_ooi size

Revision ID: 65a39ab3e224
Revises: e2f76e95f1e7
Create Date: 2022-11-17 13:28:05.911897

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "65a39ab3e224"
down_revision = "e2f76e95f1e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "boefje_meta",
        "organization",
        existing_type=sa.VARCHAR(length=4),
        type_=sa.String(length=8),
        existing_nullable=False,
    )
    op.alter_column(
        "boefje_meta",
        "input_ooi",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "boefje_meta",
        "input_ooi",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "boefje_meta",
        "organization",
        existing_type=sa.String(length=8),
        type_=sa.VARCHAR(length=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
