"""Add environment and runnable hash columns

Revision ID: d216ad75177d
Revises: 09a2929108d9
Create Date: 2023-06-19 13:55:14.188026

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d216ad75177d"
down_revision = "09a2929108d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boefje_meta", sa.Column("environment", sa.JSON(), nullable=True))
    op.add_column("boefje_meta", sa.Column("runnable_hash", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boefje_meta", "runnable_hash")
    op.drop_column("boefje_meta", "environment")
    # ### end Alembic commands ###
