"""Increase organization id length

Revision ID: ebc7de8be4e3
Revises: e09d8780e34b
Create Date: 2023-01-31 11:08:42.920579

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ebc7de8be4e3"
down_revision = "e09d8780e34b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "boefje_meta",
        "organization",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "boefje_meta",
        "organization",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
