"""Add index on BoefjeMeta table: organization_boefje_id

Revision ID: fa64454868a9
Revises: ebc7de8be4e3
Create Date: 2023-03-29 08:23:08.521462

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "fa64454868a9"
down_revision = "ebc7de8be4e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("organization_boefje_id", "boefje_meta", ["organization", "boefje_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("organization_boefje_id", table_name="boefje_meta")
    # ### end Alembic commands ###
