# Generated by Django 3.2.4 on 2021-07-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_alter_organization_octopoes_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="octopoes_host",
        ),
        migrations.AddField(
            model_name="job",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tools.organization",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="code",
            field=models.CharField(default=None, max_length=8, null=True, unique=True),
        ),
    ]
