# Generated by Django 3.2.13 on 2022-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0019_alter_scanprofile_remove_level_and_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("can_switch_organization", "Can switch organization"),
                    ("can_scan_organization", "Can scan organization"),
                )
            },
        ),
        migrations.RemoveField(
            model_name="scanprofile",
            name="is_source_ooi",
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
