
= Hardening OpenKAT

Hardening is het veilig maken van je omgeving. De standaard installatie van OpenKAT is geschikt voor lokaal gebruik. Installeer je de software in een productieomgeving, zorg dan dat je een veilige configuratie draait. De volgende aanpassingen zijn een eerste stap: 

== Password Django installatie

In de django config (/admin op rocky) moet het standaard password van de admin:admin user worden aangepast. 

== SESSION_COOKIE_AGE

Rocky is de webinterface. Deze plaatst cookies voor sessies van 1209600 seconden, of 2 weken. Dit is vrij lang en kan worden aangepast met een nieuwe entry in rocky/settings.py. 
Sessies zijn beperkt tot 2 uur op basis van de default configuratie. 

 
== Security headers

Rocky verwacht een reverse proxy die TLS kan afhandelen. Dit is een goede plek om de security headers in te stellen: 

[cols="1,m", options="header"]
|===

| Header
| Settings

| X-Frame-Options
| Deny

| X-Content-Type-Options
| nosniff

| Content-Security-Policy
| default-src 'self'; object-src 'none'; child-src 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content

| X-Permitted-Cross-Domain-Policies
| none

| Referrer-Policy
| no-referrer

| Clear-Site-Data
| "cache","cookies","storage" (Optioneel bij reverse NGINX proxies, "cookies" weglaten)

| Cross-Origin-Embedder-Policy (COEP)
| require-corp

| Cross-Origin-Opener-Policy (COOP)
| same-origin

| Cross-Origin-Resource-Policy (CORP)
| same-origin

| Permissions-Policy
| accelerometer=(),autoplay=(),camera=(),display-capture=(),document-domain=(),encrypted-media=(),fullscreen=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),midi=(),payment=(),picture-in-picture=(),publickey-credentials-get=(),screen-wake-lock=(),sync-xhr=(self),usb=(),web-share=(),xr-spatial-tracking=()

| Cache-Control
| no-store, max-age=0

| Pragma
| no-cache

| X-DNS-Prefetch-Control
| off

| Expect-CT
| max-age=86400, enforce

|=== 


== SSL/TLS on nginx

Gebruik de volgende versies en settings voor SSL/TLS op nginx:  

* ssl_protocols TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE

* ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
* ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
* ssl_session_tickets off; # Requires nginx >= 1.5.9
* ssl_stapling on; # Requires nginx >= 1.3.7
* ssl_stapling_verify on; # Requires nginx => 1.3.7
* ssl_prefer_server_ciphers on;
* ssl_session_timeout  10m;
* ssl_session_cache shared:SSL:10m;

Optioneel is het gebruik van HSTS, ook voor de subdomains. 

``add_header Strict-Transport-Security "max-age=31104000;" always;``

== Obscuring errors to the clients:

Standaard zijn errors in OpenKAT zichtbaar voor de gebruiker. De reverse proxy kan dit beperken en een algemene foutmelding geven. 

``proxy_intercept_errors on;
error_page 500 502 503 504 /error.html;``

Daarnaast is het zinvol om te voorkomen dat de proxy zelf zijn versie meestuurt met elk antwoord: 

``server_tokens off;``

== Web Application Firewall

De installatie van Rocky achter een WAF levert een extra beveiligingslaag op. Hiervoor kan modsecurity worden gebruikt, die onderdeel is van de reverse proxy. Meer informatie is te vinden op de Github pagina van het project: 

* https://github.com/SpiderLabs/ModSecurity
* https://github.com/SpiderLabs/ModSecurity-nginx

== Verder lezen

Er is veel meer informatie beschikbaar over dit onderwerp. Bij toepassing van OpenKAT in een productieomgeving bieden de volgende links een eerste stap: 

* https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/web_application_security
* https://owasp.org/www-project-secure-headers/
* https://docs.djangoproject.com/en/4.0/topics/security/




