name: Boefjes Test (with coverage)

on:
  workflow_call:

jobs:
  Tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Install pip
        run: python3 -m pip install --upgrade pip wheel

      - name: Install dev requirements
        run: grep -v git+https:// requirements-dev.txt | pip install -r /dev/stdin && grep git+https:// requirements-dev.txt | pip install -r /dev/stdin
        working-directory: boefjes/

      - name: Install plugin requirements
        run: find boefjes/plugins/ -name requirements.txt -execdir pip install -r requirements.txt \;
        working-directory: boefjes/

      - name: Install Octopoes
        run: cd octopoes && python setup.py bdist_wheel && pip install dist/octopoes*.whl

      - name: Run pytests
        run: python3 -m pytest --cov boefjes/ --cov-report xml --cov-branch boefjes/tests

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: boefjes-coverage-unit
          path: coverage.xml
