name: Boefjes Create container image

on:
  push:
    paths:
      - boefjes/**
      - octopoes/**
      - .github/workflows/boefjes_container_image.yml
  pull_request:
    paths:
      - boefjes/**
      - octopoes/**
      - .github/workflows/boefjes_container_image.yml

jobs:
  create_container_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/nl-kat-boefjes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version.py
        run: |
          pip install setuptools-scm==7.1.0
          python -m setuptools_scm
          cp _version.py boefjes/boefjes/version.py
          cp _version.py boefjes/boefjes/katalogus/version.py

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          # We don't use git context because that doesn't process .dockerignore
          # https://github.com/docker/cli/issues/2827
          context: .
          file: boefjes/Dockerfile
          push: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
