name: Bytes package bytes

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - name: Replace version number with release version
        run: find . -type f -name 'version.py' -exec sed -ibak "s/__version__ = .*/__version__ = \"${RELEASE_VERSION}\"/" {} \;
        working-directory: ./bytes

      - name: Create bytes release
        run:  tar -cvzf ../../bytes_${{ env.RELEASE_VERSION }}.tar.gz --exclude=./.git* .
        working-directory: ./bytes

      - name: Upload bytes tar
        uses: actions/upload-artifact@v1
        with:
          name: bytes_${{ env.RELEASE_VERSION }}
          path: ../bytes_${{ env.RELEASE_VERSION }}.tar.gz
