name: Check dependencies

on:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "*"
    paths:
      - "**/requirements.txt"
      - "**/requirements-dev.txt"
      - "**/pyproject.toml"
      - "**/uv.lock"
      - ".github/workflows/check_requirements.yml"
  pull_request:
    paths:
      - "**/requirements.txt"
      - "**/requirements-dev.txt"
      - "**/pyproject.toml"
      - "**/uv.lock"
      - ".github/workflows/check_requirements.yml"

jobs:
  poetry-dependencies:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: py313
        with:
          python-version: 3.13
          cache: pip

      - name: Install uv
        run: pip install uv==0.7.13

      - name: Check, lock, and export requirements
        run: make requirements

      - name: Check if there are any changed files
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: git diff --exit-code

      - name: Commit, sign, and push changes
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: bash .github/scripts/commit_sign_push.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION_BRANCH: ${{ github.ref }}
