name: Check the coding style


on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  Check:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup environment
        run: pip install -r requirements-dev.txt

      - name: Run black and mypy checks
        run: make check
