name: Debian packages

on:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "*"
  pull_request:

jobs:
  changes:
    permissions: {}
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        if: github.event_name != 'push'
        id: filter
        with:
          filters: |
            boefjes:
              - 'boefjes/**'
              - 'octopoes/**'
              - '.github/workflows/debian_package.yml'
            bytes:
              - 'bytes/**'
              - '.github/workflows/debian_package.yml'
            cveapi:
              - 'cveapi/**'
              - '.github/workflows/debian_package.yml'
            mula:
              - 'mula/**'
              - '.github/workflows/debian_package.yml'
            octopoes:
              - 'octopoes/**'
              - '.github/workflows/debian_package.yml'
            rocky:
              - 'rocky/**'
              - 'octopoes/**'
              - '.github/workflows/debian_package.yml'

  build:
    permissions:
      contents: read
    needs: changes
    if: ${{ github.event_name == 'push' || (needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '') }}
    strategy:
      fail-fast: false
      matrix:
        dist: [debian12, debian13, ubuntu22.04, ubuntu24.04]
        # On main, release branches and tags we always want to build all the packages
        package: ${{ github.event_name == 'push' && fromJSON('["boefjes", "bytes", "cveapi", "mula", "octopoes", "rocky"]') || fromJSON(needs.changes.outputs.packages) }}
        exclude:
          - { package: cveapi, dist: debian13 }
          - { package: cveapi, dist: ubuntu22.04 }
          - { package: cveapi, dist: ubuntu24.04 }
    runs-on: ubuntu-24.04
    env:
      PKG_NAME: kat-${{ matrix.package }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate version.py and set RELEASE_VERSION
        run: |
          pip install setuptools-scm==7.1.0
          echo "RELEASE_VERSION=$(python -m setuptools_scm | sed s/rc/~rc/)" >> $GITHUB_ENV
          cp _version.py boefjes/boefjes/version.py
          cp _version.py boefjes/boefjes/katalogus/version.py
          cp _version.py bytes/bytes/version.py
          cp _version.py mula/scheduler/version.py
          cp _version.py octopoes/octopoes/version.py
          cp _version.py rocky/rocky/version.py

      - name: Run debian package build
        uses: maus007/docker-run-action-fork@5ddaad0f7eedd03f64e412b1931852bd3031b273
        with:
          run: packaging/scripts/build-debian-package.sh
          registry: docker.underdark.nl
          image: docker.underdark.nl/librekat/openkat-${{ matrix.dist }}-build-image:latest
          username: ${{ secrets.librekat_user }}
          password: ${{ secrets.librekat_password }}
          options: -v ${{ github.workspace }}/${{ matrix.package }}:/app
            -v ${{ github.workspace }}/octopoes:/octopoes
            -e REPOSITORY=${{ github.repository }}
            -e RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            -e RELEASE_TAG=${{ env.RELEASE_TAG }}
            -e PKG_NAME=${{ env.PKG_NAME }}
            --workdir /app

      - name: Upload .deb to artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{env.PKG_NAME}}_${{ env.RELEASE_VERSION }}_${{ matrix.dist }}.deb
          path: ${{matrix.package}}/build/${{env.PKG_NAME}}_${{ env.RELEASE_VERSION }}_${{ matrix.package == 'cveapi' && 'all' || 'amd64' }}.deb

  add-debian-packages-to-release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate version.py and set RELEASE_VERSION
        run: |
          pip install setuptools-scm==7.1.0
          echo "RELEASE_VERSION=$(python -m setuptools_scm | sed s/rc/~rc/)" >> $GITHUB_ENV

      - name: Download all assets for debian12
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: kat-debian12-${{ env.RELEASE_VERSION }}
          merge-multiple: true
          pattern: kat-*_debian12.deb

      - name: Download all assets for ubuntu22.04
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: kat-ubuntu22.04-${{ env.RELEASE_VERSION }}
          merge-multiple: true
          pattern: kat-*_ubuntu22.04.deb

      - name: Download all assets for debian13
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: kat-debian13-${{ env.RELEASE_VERSION }}
          merge-multiple: true
          pattern: kat-*_debian13.deb

      - name: Download all assets for ubuntu24.04
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: kat-ubuntu24.04-${{ env.RELEASE_VERSION }}
          merge-multiple: true
          pattern: kat-*_ubuntu24.04.deb

      - name: Move cve-api asset to add it as a separate artifact
        run: mv kat-debian12-${{ env.RELEASE_VERSION }}/kat-cveapi_${{ env.RELEASE_VERSION }}_all.deb .

      - name: Bundle assets
        run: |
          tar -cvzf kat-debian12-${{ env.RELEASE_VERSION }}.tar.gz -C kat-debian12-${{ env.RELEASE_VERSION }} .
          tar -cvzf kat-debian13-${{ env.RELEASE_VERSION }}.tar.gz -C kat-debian13-${{ env.RELEASE_VERSION }} .
          tar -cvzf kat-ubuntu22.04-${{ env.RELEASE_VERSION }}.tar.gz -C kat-ubuntu22.04-${{ env.RELEASE_VERSION }} .
          tar -cvzf kat-ubuntu24.04-${{ env.RELEASE_VERSION }}.tar.gz -C kat-ubuntu24.04-${{ env.RELEASE_VERSION }} .

      - name: Add Release Assets
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          generate_release_notes: true
          files: |
            kat-debian12-${{ env.RELEASE_VERSION }}.tar.gz
            kat-ubuntu22.04-${{ env.RELEASE_VERSION }}.tar.gz
            kat-debian13-${{ env.RELEASE_VERSION }}.tar.gz
            kat-ubuntu24.04-${{ env.RELEASE_VERSION }}.tar.gz
            kat-cveapi_${{ env.RELEASE_VERSION }}_all.deb
