name: Keiko Run the unit tests

on:
  push:
    paths:
      - keiko/**
  pull_request:
    paths:
      - keiko/**

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [ '3.8', '3.9', '3.10', '3.11' ]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip' # caching pip dependencies

      - name: Install Latex
        run: |
          sudo apt-get install -y --no-install-recommends \
            chktex \
            fonts-recommended \
            latexmk \
            texlive-fonts-recommended \
            texlive-lang-european \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-latex-recommended \
            texlive-xetex

      - name: Install requirements-dev.txt
        run: pip install -r requirements-dev.txt
        working-directory: ./keiko

      - name: Create writeable directory for reports (edge case for GitHub Actions)
        run: mkdir -p /tmp/keiko/reports && chmod -R 700 /tmp/keiko/reports

      - name: Run unit tests
        run: make test
        working-directory: ./keiko
        env:
          KEIKO_REPORTS_FOLDER: /tmp/keiko/reports
