name: Keiko Build python virtual env and package

on:
  create:
    tags:
      - v*
  push:
    branches:
      - package

env:
  PKGNAME: katkeiko

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1

      - name: Replace version number with release version
        run: find . -type f -name 'version.py' -exec sed -ibak "s/__version__ = .*/__version__ = \"${RELEASE_VERSION}\"/" {} \;
        working-directory: ./keiko

      - name: Configure git
        run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: prep
        run: sudo mkdir -p /var/www/html
      - name: prep chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: copy project to run location.
        run: cp -r * /var/www/html
        working-directory: ./keiko

      - name: Create env
        run: python3.8 -m venv /var/www/html/.venv

      - name: Install requirements
        run: source .venv/bin/activate; pip install --upgrade pip; find . -name requirements.txt | xargs -L 1 pip install -r
        working-directory: /var/www/html

      - name: Create archive
        run: tar -zcvf ../${{ env.PKGNAME }}_venv_${{ env.RELEASE_VERSION }}.tar.gz -C /var/www/html/ .venv

      - name: Create ${{ env.PKGNAME }} release
        run:  tar -cvzf ../../${{ env.PKGNAME }}_${{ env.RELEASE_VERSION }}.tar.gz .
        working-directory: ./keiko

      - name: Upload tar
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.PKGNAME }}_${{ env.RELEASE_VERSION }}
          path: ../${{ env.PKGNAME }}_${{ env.RELEASE_VERSION }}.tar.gz

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.PKGNAME }}_venv_${{ env.RELEASE_VERSION }}
          path: ../${{ env.PKGNAME }}_venv_${{ env.RELEASE_VERSION }}.tar.gz
