name: Octopoes package octopoes

on:
  push:
    tags:
      - v*
    branches:
      - "packaging"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Replace version number with release version
        run: find . -type f -name 'version.py' -exec bash -c "echo __version__ = \'${RELEASE_VERSION}\' > {}" \;
        working-directory: ./octopoes

      - name: prep
        run: sudo mkdir -p /var/www/html

      - name: prep chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: copy project to run location.
        run: cp -r * /var/www/html
        working-directory: ./octopoes

      - name: Build whl package
        run: |
          python3.8 -m pip install build
          python3.8 -m build
        working-directory: ./octopoes

      - name: Upload whl package
        uses: actions/upload-artifact@v2
        with:
          name: "octopoes/octopoes-${{env.RELEASE_VERSION}}"
          path: "dist/octopoes-*.whl"

      - name: Create env
        run: python3.8 -m venv /var/www/html/.venv

      - name: Install requirements
        run: cd /var/www/html; source .venv/bin/activate; pip install --upgrade pip; pip install --requirement requirements.txt

      - name: Create venv archive
        run: tar -zcvf ../octopoes_venv_${{ env.RELEASE_VERSION }}.tar.gz -C /var/www/html/ .venv

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: octopoes_venv_${{ env.RELEASE_VERSION }}
          path: ../octopoes_venv_${{ env.RELEASE_VERSION }}.tar.gz

      - name: Enable production logging config
        run: mv prod.logging.yml logging.yml
        working-directory: ./octopoes

      - name: Create Octopoes release
        run:  tar -cvzf ../../octopoes_${{ env.RELEASE_VERSION }}.tar.gz .
        working-directory: ./octopoes

      - name: Upload octopoes tar
        uses: actions/upload-artifact@v1
        with:
          name: octopoes_${{ env.RELEASE_VERSION }}
          path: ../octopoes_${{ env.RELEASE_VERSION }}.tar.gz
