name: Octopoes Tests (with coverage)

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies

      - name: Install requirements
        run: pip install -r requirements-dev.txt
        working-directory: octopoes/

      - name: Run unit tests
        run: pytest --cov octopoes/ tests/
        working-directory: octopoes/

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: octopoes-coverage-unit
          path: octopoes/.coverage
          include-hidden-files: true

  integration-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Run integration tests
        run: make itest
        working-directory: octopoes/

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: octopoes-coverage-integration
          path: octopoes/.coverage
          include-hidden-files: true

  coverage:
    runs-on: ubuntu-24.04
    needs:
      - unit-tests
      - integration-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies

      - name: Install coverage
        run: pip install coverage[toml]

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: octopoes-coverage-*

      - name: Merge and generate coverage report
        run: |
          coverage combine ../**/.coverage
          coverage report
          coverage xml --ignore-errors
        working-directory: octopoes/

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: octopoes-coverage
          path: octopoes/coverage.xml
