name: Octopoes Run the robot framework integration tests with Crux (regression)

on:
  push:
    paths:
      - octopoes/**
  pull_request:
    paths:
      - octopoes/**

jobs:
  rtest:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies

      - name: Install requirements-dev.txt
        run: pip install -r requirements-dev.txt
        working-directory: ./octopoes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Run robot tests on Crux (regression)
        run: make rtest-crux
        env:
          DOCKER_BUILDKIT: 1
        working-directory: ./octopoes
