name: Octopoes Run the robot framework integration tests

on:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "*"
    paths:
      - octopoes/**
      - .github/workflows/octopoes_rtest.yml
  pull_request:
    paths:
      - octopoes/**
      - .github/workflows/octopoes_rtest.yml

jobs:
  rtest:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Install requirements-dev.txt
        run: pip install -r requirements-dev.txt
        working-directory: ./octopoes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Run robot tests
        run: make rtest
        env:
          DOCKER_BUILDKIT: 1
        working-directory: ./octopoes
