name: Octopoes Tests (with coverage)

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Install requirements
        run: pip install -r requirements-dev.txt
        working-directory: octopoes/

      - name: Run unit tests
        run: pytest --cov octopoes/ octopoes/tests/

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: octopoes-coverage-unit
          path: coverage.xml
