name: Rocky package rocky

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - name: Replace version number with release version
        run: find . -type f -name 'version.py' -exec sed -ibak "s/__version__ = .*/__version__ = \"${RELEASE_VERSION}\"/" {} \;
        working-directory: ./rocky

      - name: Configure git
        run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: prep
        run: sudo mkdir -p /var/www/html

      - name: prep chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: copy project to run location.
        run: cp -r * /var/www/html
        working-directory: ./rocky

      - name: Create env
        run: python3.8 -m venv /var/www/html/.venv

      - name: Build Octopoes wheel
        run: cd octopoes && /usr/bin/python3 setup.py bdist_wheel

      - name: Install requirements
        run: cd /var/www/html; source .venv/bin/activate; pip install --upgrade pip; pip install --requirement requirements.txt; pip install ${{ github.workspace }}/octopoes/dist/octopoes*.whl

      - name: Install gettext
        run: sudo apt install gettext -y

      - name: Create archive
        run: tar -zcvf ../rocky_venv_${{ env.RELEASE_VERSION }}.tar.gz -C /var/www/html/ .venv

      - name: Run nvm install
        run: nvm install v16
        shell: bash --login {0}
        working-directory: ./rocky

      - name: Run nvm use
        run: nvm use
        shell: bash --login {0}
        working-directory: ./rocky

      - name: Run yarn for rocky
        run: yarn
        shell: bash --login {0}
        working-directory: ./rocky

      - name: Run yarn build for rocky
        run: yarn build
        shell: bash --login {0}
        working-directory: ./rocky

      - name: Collectstatic
        run: SECRET_KEY="boeitniet" /var/www/html/.venv/bin/python3.8 manage.py collectstatic
        working-directory: ./rocky

      - name: Compilemessages
        run: SECRET_KEY="boeitniet" /var/www/html/.venv/bin/python3.8 manage.py compilemessages
        working-directory: ./rocky

      - name: Create rocky release
        run: tar -cvzf ../../rocky_${{ env.RELEASE_VERSION }}.tar.gz --exclude node_modules --exclude rocky_venv* --exclude=.git* --exclude .parcel-cache --exclude Dockerfile .
        working-directory: ./rocky

      - name: Upload rocky tar
        uses: actions/upload-artifact@v1
        with:
          name: rocky_${{ env.RELEASE_VERSION }}
          path: ../rocky_${{ env.RELEASE_VERSION }}.tar.gz

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: rocky_venv_${{ env.RELEASE_VERSION }}
          path: ../rocky_venv_${{ env.RELEASE_VERSION }}.tar.gz
