name: Rocky Tests (with coverage)

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: make utest
        working-directory: rocky/

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rocky-coverage-unit
          path: rocky/.coverage
          include-hidden-files: true

  integration-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Run integration tests
        run: make itest
        working-directory: rocky/

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rocky-coverage-integration
          path: rocky/.coverage
          include-hidden-files: true

  coverage:
    runs-on: ubuntu-24.04
    needs:
      - unit-tests
      - integration-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Install coverage
        run: pip install coverage[toml]

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: rocky-coverage-*

      - name: Merge and generate coverage report
        run: |
          coverage combine ../**/.coverage
          coverage report
          coverage xml --ignore-errors
        working-directory: rocky/

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rocky-coverage
          path: rocky/coverage.xml
