# Generated by Django 3.2.18 on 2023-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ooi_type", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("content", models.CharField(max_length=128)),
                ("link", models.URLField(max_length=256)),
            ],
        ),
    ]
