# Generated by Django 3.2.18 on 2023-05-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tools", "0039_update_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginDeepLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ooi_type", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("content", models.CharField(max_length=128)),
                ("link", models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationPlugin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField()),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tools.organization"),
                ),
                (
                    "plugin",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="katalogus.plugindeeplink"),
                ),
            ],
            options={
                "unique_together": {("organization", "plugin")},
            },
        ),
    ]
