# Generated by Django 4.2.1 on 2023-06-05 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("katalogus", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="plugindeeplink",
            unique_together={("ooi_type", "name")},
        ),
    ]
